version: "3"

services:
  nginx:
    image: nginx:1.17.2
    ports:
      - 8040:80
      - 443:443
    volumes:
      - ./apps:/var/www/html/:rw
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf/:rw
      - ./logs/nginx/:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  php72:
    build:
      context: .
    volumes:
      - ./apps:/var/www/html/:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./logs/php/:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /data/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis.conf:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8083:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8089:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  default: